### ISSUE TITLE
Performance impact from ChestShop::Event: c.A.C.L.I.ItemMoveListener (InventoryMoveItemEvent)

### ISSUE THREAD

**Issue by mibby** [ChestShop-authors/ChestShop-3#109]
Paper dev 1322 (Spigot 1.12.2) - https://ci.destroystokyo.com/job/Paper/
WorldGuard dev 1712 - http://builds.enginehub.org/
ChestShop dev 62 - https://ci.minebench.de/view/All/job/ChestShop-3/

I ran a timings profile earlier today and noticed most of my lag stems from ChestShop and WorldGuard, specifically the InventoryMoveItemEvent for both. Is there anything that can be done to further improve and optimize this event used in the plugin?

Timings profile.
https://timings.aikar.co/?id=c6ccbd224d894c3690de6e78aac5d082#timings

ChestShop config
https://paste.ubuntu.com/26522272/

WorldGuard config
https://paste.ubuntu.com/26522275/

**Comment by Phoenix616** [comment]
Performance with the InventoryMoveItemEvent and Hoppers are in general an issue. This is both due to the large amounts of events that get fired (e.g. with many hoppers; or due to the event being an attempt and not an actual move which comes into play when hoppers try to transfer items into full containers) 

More information about Hopper issues can be found in PaperMC/Paper#392.

Possible ways to fix this:
1. Remove hopppers
2. Turn off Hopper protection in the config
3. Wait for/apply [Aikar's Hopper optimization PR](https://github.com/PaperMC/Paper/pull/976).
4. Use my [HopperImprovements plugin](https://github.com/Minebench/HopperImprovements) to cancel events for full chests or completely disable the events

I will also look into adding an alternative Hopper protection to ChestShop, similar to the one I [added](https://github.com/Minebench/LWC/tree/feature/alternative-hopper-protection) to my LWC fork so that non-Paper servers could also benefit from some performance improvements.

**Comment by Phoenix616** [comment]
The item move listener (when enabled) will now only listen for Hopper Minecarts since commit 7adf02e532896be2217646171a9607183d960ff5 (Hoppers and Droppers are checked on place), that should lead to a bit of performance improvement because the listener now aborts for most moves before expensive calls to BlockState#getBlock or the searching of the shop sign. I assume this as fixed unless additional timings with the new changes turn up.

**Comment by BirkhoffLee** [comment]
The issue is still there!
![](https://i.imgur.com/ljXR2PO.png)
