### ISSUE TITLE
IllegalArgumentException: Cannot generate code for item ItemStack{WOOL x 33} with maximum length of 0

### ISSUE THREAD

**Issue by mibby** [ChestShop-authors/ChestShop-3#114]
ChestShop dev 63

Wool shops no longer seem to work after updating dev builds. You can't seem to  ```/iinfo``` wool or dyes .

```
[22:34:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iinfo' in plugin ChestShop v3.9.1-SNAPSHOT (build 63)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1349]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1349]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{WOOL x 33} with maximum length of 0
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:238) ~[ChestShop.jar:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:139) ~[ChestShop.jar:?]
	at com.Acrobot.ChestShop.Commands.ItemInfo.onCommand(ItemInfo.java:39) ~[ChestShop.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1349]
	... 15 more
```

**Comment by DrPanic** [comment]
I got this error in build 64 with some banners now:
![2018-03-14_15 26 41](https://user-images.githubusercontent.com/5235435/37409667-25b35c92-279f-11e8-99bb-2b60f3032e1b.png)

**Comment by Phoenix616** [comment]
Unfortunately I cannot reproduce this with a banner? Can you provide more info about the item that produces this error? How exactly are your obtaining this item? If via a command then please provide that, otherwise it might be useful to provide the NBT/player.dat.

**Comment by DrPanic** [comment]
The error occour not by all the banners. This one will fail: `/give @p minecraft:banner 1 0 {BlockEntityTag:{Base:12,Patterns:[{Pattern:bs,Color:10},{Pattern:mc,Color:15},{Pattern:cre,Color:0},{Pattern:flo,Color:15}]}}`

The Banner in the shop is crafted like this (https://www.planetminecraft.com/banner/sheep-18357/) . I will check the build 63 now.

**Comment by DrPanic** [comment]
The error is also in build 63.

**Comment by Phoenix616** [comment]
Hm, that seems to be happening due to the base color being defined in the data instead of as the damage value. (Minecraft even gives a banner with a black base and base color is stripped when serialising which results in this error) Not sure yet why this happens or how to bypass that..

Banners that are crafted normally/don't contain the base color tag should work just fine though.

**Comment by Phoenix616** [comment]
51495cdefbddbf194e381dec92a508b73a6f7009 should fix the banner issues.

**Comment by DrPanic** [comment]
No, unfortunately not :-/ The banners are normally crafted.

`15.03 14:00:36 [Server] INFO DrPanic issued server command: /iinfo 15.03 14:00:36 [Server] ERROR null 15.03 14:00:36 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'iinfo' in plugin ChestShop v3.9.1-SNAPSHOT (build 65) 15.03 14:00:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?] 15.03 14:00:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO at java.lang.Thread.run(Thread.java:844) [?:?] 15.03 14:00:36 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{BANNER x 4, BANNER_META:{meta-type=BANNER, patterns=[org.bukkit.block.banner.Pattern@9e99bc8b, org.bukkit.block.banner.Pattern@1c5ad8d8, org.bukkit.block.banner.Pattern@886ec678, org.bukkit.block.banner.Pattern@190e099]}} with maximum length of 0(tried code Light Blue Banner#zx 15.03 14:00:36 [Server] INFO at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:219) ~[?:?] 15.03 14:00:36 [Server] INFO at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:152) ~[?:?] 15.03 14:00:36 [Server] INFO at com.Acrobot.ChestShop.Commands.ItemInfo.onCommand(ItemInfo.java:39) ~[?:?] 15.03 14:00:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1349] 15.03 14:00:36 [Server] INFO ... 15 more`

**Comment by Phoenix616** [comment]
I'm not exactly sure how you manage to do that. When I craft the banner that you linked it works without any issues? (I'm using the same server version as you)

**Comment by DrPanic** [comment]
I checked this on a blank server. It worked there. I found out that the error is caused by our items.db
Do you have an idea why this is happening?

**Comment by Phoenix616** [comment]
I suspected something like that. Can you provide me with your items.db so that I can take a look at what data it stored?

**Comment by DrPanic** [comment]
Sure, here it is:
http://puu.sh/zITqY/3893521eda.db

Thank you for your support!

**Comment by Phoenix616** [comment]
Thanks. As far as I can tell from a quick look this doesn't seem to be an issue with banners per se. For whatever reason it is returning the code of a completely unrelated item... maybe some form of collision?

**Comment by Phoenix616** [comment]
Ok I found the real issue: It was lowercasing the Metadata ID which obviously resulted in a completely different item so when it compared the two it threw this error.

**Comment by Phoenix616** [comment]
If this issue is still happening to you on a different build/server version then please open a new issue and provide the information requested in the issue template.

Otherwise if it's the exact same version and items as in this ticket then please provide your log, sign setup and exact server&plugin version here.
