### ISSUE TITLE
**BREAKING** DUPE

### ISSUE THREAD

**Issue by Agazed** [ChestShop-authors/ChestShop-3#118]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
3.9.1-SNAPSHOT build 65 (67 does not work for me shown in previous issue)
 
#### Plugin Config
default
 
#### Server Version
PaperSpigot 1.8.8
 
#### Server Log
Not even needed, no exception produced

#### What other plugins are you running?
Doesn't matter

#### What is happening?
There is a major dupe glitch. Using /iteminfo on a written book, then making a sell shop for that book. When a player sells their book, it is not taken from their inventory but is added to the chest shop and money is transferred.

#### What did you expect to happen?
It to take the item? Why do you have these dumb ass questions do you think i'm retarded?

Please provide any additional info below
Players discovered this dupe and used to to trade villagers for emeralds raking in millions

**Comment by Phoenix616** [comment]
Cannot reproduce on the latest server (1.12.2) and the latest build.

**Comment by Phoenix616** [comment]
This behaviour is probably caused by a bug which was introduces in 6e9824e6b040c9b7f456a4bd8543284d491397a6 (build 63) and fixed in dd44217132aed391579ee07e38b2352e3ca445a5 (build 66)

**Comment by Agazed** [comment]
Works on build 62 so I don't think so. This dupe should be fixed, as so many servers still run 1.8. It also says it's supported on the bukkit dev page. I don't understand why you would dismiss a large portion of servers that still run this plugin and are suspect to this breaking dupe.

**Comment by Phoenix616** [comment]
Ok so I did some investigating into this problem and it seems to be an issue with how this outdated server version handles books and not anything the plugin itself does wrong. For now I suggest denying the permission to sell and buy written books.

I'm thinking about if it could be possible to fix that but supporting outdated server versions is (again) causing a lot of headaches and I'm not sure it's worth it especially when [most servers](https://bstats.org/plugin/bukkit/ChestShop) already run on updated version and the issue is already fixed in later server versions.

**Comment by Agazed** [comment]
Whats the perm to blacklist written book?

**Comment by Agazed** [comment]
I seriously hope you can fix this. 15% of servers still run 1.8, which I would consider a large amount.

**Comment by Phoenix616** [comment]
Due to the severity of this bug I decided to create a branch that is compatible with 1.8.8 to include the fix. (It's in [build 68](https://ci.minebench.de/job/ChestShop-3/68/)) Gonna have to think about how to do that in the future, maybe I move that to a separate build job that only includes 1.8.8 hotfixes.

**Comment by Agazed** [comment]
Thanks for supporting the last good decent version of minecraft <3
