### ISSUE TITLE
PLAYER_NOT_FOUND

### ISSUE THREAD

**Issue by YellowZaki** [ChestShop-authors/ChestShop-3#125]
Can we turn off the users database on offline servers? I don't want to have the database. 
I often delete and players get the PLAYER_NOT_FOUND message because the player of the shop have to join the server.

I think these issue didn't occur on older versions. I could delete the database and player were able to shop without getting PLAYER_NOT_FOUND.

**Comment by Phoenix616** [comment]
No, even in offline mode the database is necessary in order to store sign-name to username mappings as signs are not always able to hold the 16 characters that a username can have. (It's limited by 15 characters)

Just don't delete the database, if you want to make it smaller you can remove the entries from inactive players but deleting/non-existing players cannot be supported.
