### ISSUE TITLE
1.13.2 console error

### ISSUE THREAD

**Issue by comonier** [ChestShop-authors/ChestShop-3#183]
paper 1.13.2 (build 411)
chestshop 3.9.3 snapshot build 106

console error: https://codeshare.io/arxvqA
config: https://codeshare.io/GAOZDe

I use the world guard and the red protection I do not know if one of these two plugins is blocking the player from interacting with the sign

example: trying to sell 1 pack of wheat
on a sign of chestshop where i setup hu3shop / 2034 / s 2304 / wheat
https://codeshare.io/2KnroX

**Comment by Phoenix616** [comment]
There isn't really anything obvious in that error that points towards an issue inside the plugin. Not sure though if that#s due to some missing parts (it says skipped lines at the bottom, can you maybe provide the full error including the messages before and after it from the log?) or maybe because it's an error in the server itself?

**Comment by comonier** [comment]
solve after last dev update
