### ISSUE TITLE
Admin use of other's chestshops broke somewhere between build 93 and build 113

### ISSUE THREAD

**Issue by Momshroom** [ChestShop-authors/ChestShop-3#201]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
3.9.3-SNAPSHOT (build 113)

#### Plugin Config
https://pastebin.com/gYbihYv9

(Please note, I've tried both true and false for this value:
IGNORE_ACCESS_PERMS: true
The results are the same.

#### Server Version
 CraftBukkit version git-Spigot-b0f4c22-a2dd0e3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

#### Server Log
Nothing to see here, but:
https://pastebin.com/inKyZf44

#### What other plugins are you running?
[List of your plugins, ideally with the version] 
This is not a short list, and likely not relevant, other than that we are running Towny, LWC (Modern), Vault, TNE, CMI, luckperms and Worldguard.
If you need more, just ask, or it's in the bootup log.

#### What is happening?
There is no console error.  When an admin attempts to buy or sell to a shop by clicking on the sign, the shop just opens as though the admin were the shop owner or were clicking on the chest rather than the sign.  

I have noticed that the changelog on Jenkins reports this being fixed a few times... it appears to be broken again.

#### What did you expect to happen?

I would expect the admin to be able to buy and sell from the player shop.

Please provide any additional info below

This happens no matter how the IGNORE_ACCESS_PERMS: config line is set.

This is not affected by whether the shop in question was created by the admin in a player's name or by the player themselves.  Our admins do have LWC admin perms as well if that is relevant.

I found a related ticket  #179 but my admins are not opped and this has always worked the way I would expect in older versions... My admins have permissions to open, create, etc, signs for others, but have always (We've been using chestshop for over four years.) been able to use the shops by clicking on the signs rather than the chests, while for the actual shop owner, clicking on the sign opened it.  Upgrading from dev build 93 to 113 breaks this functionality. I don't want to remove their permissions to check other people's shops or set them up, I just want them to be able to shop at them as well.  Yes, I'm aware they could drain someone's money this way:  but if I thought they was any chance they were  going to do that, they wouldn't be admins.(Why would anyone give perms to other people's chestshops to someone that wasn't trustworthy in the first place?)..and they have economy admin perms anyway.

**Comment by Phoenix616** [comment]
Players are not able to buy from shops that they have access to. That players with the access permissions where able to do so before was actually a bug which [was fixed](https://github.com/ChestShop-authors/ChestShop-3/commit/b853afbd5223d9f6885601c60e5ec438e6721926) (and which is probably where you saw the mention of the bug).

That same commit added the new `IGNORE_ACCESS_PERMS` though which allows disabling the ignoring of people with the access permission config option so that the old behaviour is somewhat emulated. This works fine when I test it with the config option set to false (so that people with access aren't ignored) and I can successfully buy from both an admin shop and another player's shop.

**Comment by Momshroom** [comment]
This was fixed in build 115. Thank you.
