### ISSUE TITLE
Server shutdown after selling many items

### ISSUE THREAD

**Issue by masterstreamer** [ChestShop-authors/ChestShop-3#223]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
3.9.3-SNAPSHOT (build 113)
 
#### Plugin Config
https://pastebin.com/iZi9NZ14
 
#### Server Version
git-Spigot-f09662d-f40143e (MC: 1.13.2)
 
#### Server Log
Message before shutdown: https://pastebin.com/HG6nhU5H

#### What is happening?
After selling about 100 times in a short time, the server shuts down.
Newest version is very slow for me while using the id converter

**Comment by Phoenix616** [comment]
This is most likely not caused by ChestShop but by your economy plugin (as it seems to store money in MySQL. Depending on your setup that might be slow and trigger some server crash detection)

My suggestion for things you can do in ChestShop itself (besides updating it) would be to increase the `SHOP_INTERACTION_INTERVAL` to maybe a second to slow down people spamming shops and to allow selling in stacks so that they have an alternative to spamming.

**Comment by masterstreamer** [comment]
@Phoenix616 Thank you, this is a good option. I just changed that. But still, if someone buys from a shop, the server hungs for half a second. Do you know that issue?

**Comment by Phoenix616** [comment]
Well you are still using an economy plugin that seems to be doing database operations on the main thread so the speed at which transactions can process will be heavily depended on the speed of your database connection and database itself. I suggest taking a look at your server timings (and possibly a profiler) to find out what exactly is being slow there in detail.
