### ISSUE TITLE
Error while generating full item name (Book)

### ISSUE THREAD

**Issue by Bedah95** [ChestShop-authors/ChestShop-3#250]
#### Plugin Version
ChestShop v3.10-SNAPSHOT (build 149)
 
#### Plugin Config
https://pastebin.com/uV7cEFjK
 
#### Server Version
Paper 1.14.3 -122
 
#### Server Log
https://pastebin.com/DzLxLKMQ

#### What other plugins are you running?
AdvancedPortals, Animatronics*, Announcer*, ArmorStandTools, ASH, BossShopPro, ChangeSkin*, ChestShop, CommandHook, CraftBook, Deathlog*, DeathMessages*, Essentials, EssentialsChat, EssentialsSpawn, Failed2Ban*, FancyText2, HorseMaster, JCVaultListener*, Jobs, LimitedUses*, LogBlock, Logs*, Lottery*, LWC, MidiPlayer*, MsgExtender, Multiverse-Core, Multiverse-Portals, OnTime*, ParrotGlue, Party*, PerWorldInventory, Pingas*, PlaceholderAPI*, PlayerPoints*, PlotAddOn*, PlotSquared, ProtocolLib, RateOfXray*, RbayB, RougeParkour, SimpleBackup*, statuecreator*, TAB, uCars, UtiLMC, Vault, Vix*, VoteMe*, VoteNotify, Votifier*, WDLCompanion*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, zPermissions

#### What is happening?
Error while executing the command /iinfo.

#### What did you expect to happen?
Item-ID?

**Comment by Phoenix616** [comment]
Works just fine when I test it with a written book. Please provide the NBT of the item for testing.

**Comment by Bedah95** [comment]
Written book is in the chest.

https://pastebin.com/EzXWV2vR

**Comment by Phoenix616** [comment]
Basically the issue here is that serializing and deserializing the pages of a book will lead to a different item due to it coloring all of the text black. This has been [reported to Spigot](https://hub.spigotmc.org/jira/browse/SPIGOT-3206) before and apparently cannot be resolved. 

ChestShop has been using [a workaround](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/Breeze/Utils/MaterialUtil.java#L86) for that by deserializing both items and comparing the strings but apparently 1.14 broke that and now includes the black color codes in the strings too (which it didn't do previously) Now even the deserialized versions are completely different and our only solution might be to go through the (de)serialization process twice in order to properly check equality... (which is even more annoying than before)
