### ISSUE TITLE
ChestShop does not respect LWC limits.

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#293]
Setup:
PaperSpigot Build 105
Chestshop Build 171
LWCX: https://github.com/pop4959/LWCX (Latest as of this report)

TL;DR if user is at maximum limit for lwc (check via /climits) they can still create chestshops.
Config: https://pastebin.com/p7nLyx2X

**Comment by Phoenix616** [comment]
That's rather strange, ChestShop is [firing the correct event](https://github.com/ChestShop-authors/ChestShop-3/blob/3fe35cd0a5c23ed1507abb9b135c9203c8e6370f/src/main/java/com/Acrobot/ChestShop/Plugins/LightweightChestProtection.java#L105) which the LimitsModule [is listening on](https://github.com/pop4959/LWCX/blob/7def6055797aec543af1baa83503bb2db32d9337/src/main/java/com/griefcraft/modules/limits/LimitsModule.java#L388) and would cancel if the limit is reached. Is the message of the reached limit send or not? Because if not then it might be an issue with LWCX' limits module rather than ChestShop itself.

**Comment by andrewkm** [comment]
No, the max limits message doesn’t send when limit is full and you’re making a chestshop, it simply lets it go through.

**Comment by andrewkm** [comment]
@Phoenix616 with your latest changes, it allows the shop to be created, but the shop is NOT protected as the climits are reached.

As such, the bug is half fixed, (it doesn't protect the shop), however the shop should not be created in the first place if the limits are full :)

**Comment by Phoenix616** [comment]
Hm, this might require an extra config option seeing as some might want the shop to still get created but just not protected.

**Comment by andrewkm** [comment]
Any updates on this?
Not sure if it's been addressed or not yet.

**Comment by andrewkm** [comment]
@Phoenix616 please re-open, this is still broken.
Using latest chestshops and LWCX as of this post.

Config has:
```
# Should LWC limits block shop creations?
LWC_LIMITS_BLOCK_CREATION: true
```

Limits are as such:
https://i.imgur.com/g09BaUy.png

On shop creation:
https://i.imgur.com/v9FPOXP.png

**Comment by Phoenix616** [comment]
Should be fixed now. Apparently LWC has two different limit modules? :S

**Comment by andrewkm** [comment]
Ah yes, limitsv2 was released a long time ago, but indeed is the new one. :)
Thanks! Confirmed fixed :)
