### ISSUE TITLE
Per-world economy support (explained better at the thread).

### ISSUE THREAD

**Issue by IIPedro** [ChestShop-authors/ChestShop-3#319]
Hey there (again)! The title may sound very confusing, but the problem and the solutions are very simple. Any questions, ask away. I'll keep an eye on this page.

#### Is your feature request related to a problem? Please describe.
I'm using Multiverse-Core and whenever a player buys items from a shop whose player is offline, the player who owns the shop always gets the money in the lobby world.

#### Describe the solution you'd like
A very simple solution would be to make it so the player gets the money when he joins the world in which the shop he owns sold items.

#### Describe alternatives you've considered
The player receives the money when he opens the chest which sold items.

#### Additional context
The plugin supports MultiWorldMoney. If possible, please keep this compatibility.

Thank you in advance! Have a wonderful day!

**Comment by Phoenix616** [comment]
ChestShop [will give](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Listeners/Economy/Plugins/VaultListener.java#L185-L191) the money in the world that the shop is in, if your economy plugin isn't properly handling that for offline players then they have to fix this issue. (Which isn't a feature request but would be a bug report if it really was caused by ChestShop itself. Ideally the [bug template](https://github.com/ChestShop-authors/ChestShop-3/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) information would be provided in that case ;))

**Comment by IIPedro** [comment]
All right, thanks!
