### ISSUE TITLE
Java.sql.SQLException: Error opening connection

### ISSUE THREAD

**Issue by zanatarp** [ChestShop-authors/ChestShop-3#344]
#### Plugin Version
Last build (#224)
 
#### Plugin Config
Default
 
#### Server Version
1.16.1
 
#### Server Log
https://pastebin.com/89swECVE

### Additional context

SunOS solaris 5.11 11.3 sun4v

_#sqlite3 test.db
SQLite version 3.8.8.1 2015-01-20 16:51:25
Enter ".help" for usage hints.
sqlite>
sqlite>
sqlite>_

**Comment by Phoenix616** [comment]
For one you are using build 174, not 224.

Also this error seems to occur because your OS does not provide native SQLite libraries. (See lines 30 and 63) Here is an isue which might contain information regarding how to get this to work: https://github.com/xerial/sqlite-jdbc/issues/469

**Comment by pauloreloy** [comment]
@zanatarp 

This error is caused because lib sqlitejdbc for sparcv9 is unavailable natively. The lib in attachment was compiled for sparcv9.

Please follow the instructions to make it work:
unzip main server jar file:
unzip spigot.jar

Put the lib from zip in:
org/sqlite/native/SunOS/sparcv9

*** if SunOS/sparcv9 directories isnt created, create it.

Then compile all stuff again to jar:

jar cmvf META-INF/MANIFEST.MF spigot.jar *

Then run it again. Plz let me know if it works well.

[libsqlitejdbc.zip](https://github.com/ChestShop-authors/ChestShop-3/files/4939637/libsqlitejdbc.zip)

**Comment by zanatarp** [comment]
Nice bro

It's working now!
