### ISSUE TITLE
ItemBridge Support

### ISSUE THREAD

**Issue by Technofied** [ChestShop-authors/ChestShop-3#361]
#### Is your feature request related to a problem? Please describe.

There is an issue at the moment where QualityArmory, a gun plugin, uses different IDs per gun which results in our players having to manually change the ID of each ChestShop sign to sell each gun e.g.

Technofied
1
B 1
Crossbow#1d

Once that gun has sold - 

Technofied
1
B 1
Crossbow#1f

#### Describe the solution you'd like

QualityArmory has integrations with ItemBridge, so instead of needing to go Crossbow# you can go qa:<gunname> e.g. qa:grenade

However ChestShop doesn't seem to accept these values as IDs for items.

#### Describe alternatives you've considered

Having direct support for QA, but I think this solution is easier to implement.

#### Additional context

We're a city RP server, so we are in dire need of this feature.

**Comment by Phoenix616** [comment]
Sounds like it could be integrated the same way OddItem was intially, either directly in ChestShop or via an extension plugin simply handling the item and material parse events.

I took a quick look at it and is [this the plugin](https://www.spigotmc.org/resources/itembridge-save-items-and-use-them-wherever-you-want-including-other-plugins-1-16-ready.77080/) you are talking about? Because they don't really make it easy to integrate with them (no maven repo/artifact, no clear code license :S)

**Comment by Technofied** [comment]
> Sounds like it could be integrated the same way OddItem was intially, either directly in ChestShop or via an extension plugin simply handling the item and material parse events.
> 
> I took a quick look at it and is [this the plugin](https://www.spigotmc.org/resources/itembridge-save-items-and-use-them-wherever-you-want-including-other-plugins-1-16-ready.77080/) you are talking about? Because they don't really make it easy to integrate with them (no maven repo/artifact, no clear code license :S)

That is the plugin in question

**Comment by Technofied** [comment]
They seem to have a lot more information on PolyMart, if that helps - https://polymart.org/resource/4/page/info-for-developers

**Comment by Phoenix616** [comment]
Information isn't really the issue, the issue is that that don't make it
easy for others to integrate with their plugin by providing a maven
artifact to which one can depend on.

**Comment by Technofied** [comment]
Any news on this one?
