### ISSUE TITLE
Please add DiscordSRV as SoftDepend.

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#528]
### What is happening?

`[ChestShop] Loaded class org.slf4j.impl.StaticLoggerBinder from DiscordSRV v1.26.0-SNAPSHOT which is not a depend or softdepend of this plugin.`

### What did you expect to happen?

No Warning.

### Plugin Version

Latest

### Plugin Config

N/A

### Server Version

N/A

### Server Log

N/A

### What other plugins are you running?

N/A

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

### Additional context

N/A

**Comment by Phoenix616** [comment]
ChestShop has nothing to do with DiscordSRV, setting it as a soft-dependency would not make sense here. This error itself is down to your server not properly prioritising the classes and for some reason loading a class from a third-party plugin which is not in the dependency tree instead of using the one shipped with the server itself so this would need to be fixed in the server (or DiscordSRV), not in every plugin that might run into this bug.
