### ISSUE TITLE
Server crashes due to stacking function

### ISSUE THREAD

**Issue by iaxedu** [ChestShop-authors/ChestShop-3#78]
The crash happens often have not yet found out what exactly triggers it. The error report always starts with ChestShop

Paper-1226 (MC: 1.12.2)
ChestShop v3.8.13-SNAPSHOT (build #33)

https://hastebin.com/ozolelewiq.md

**Comment by Sitmobedaf** [comment]
I have same problem.

**Comment by Phoenix616** [comment]
Please provide the full thread dumps in order for us to check if this is caused by ChestShop. Just because it's at the top doesn't mean that that's what caused it. The dump just displays everything that is currently running together with their status.

**Comment by Sitmobedaf** [comment]
https://pastebin.com/9KtcG49a

**Comment by Phoenix616** [comment]
Yeah that's what I thought. That doesn't look like it's caused by ChestShop at all, especially as the lines are different and the code at that point can't really cause such a crash. It looks more like it's an issue with another plugin (both PermissionsEx or ProtocolSupport have the state "blocked") blocking the main thread and not resuming or an internal issue. (there is a third blocked thread)

If this error keeps re-occurring check for these blocked threads and if they have the same plugin thread blocked test without them.

**Comment by Sitmobedaf** [comment]
iaxedu, you have PEX or PS?

**Comment by Phoenix616** [comment]
Seems to be happening to more people. Reopening this.
