### ISSUE TITLE
e.setSignLine on PreShopCreationEvent not working somehow

### ISSUE THREAD

**Issue by DrOreo002** [ChestShop-authors/ChestShop-3#82]
I think the problem is that you didn't update the sign using sign.update :/. I want to try to edit the file but well I don't want to messed things up and I cannot use Github btw xD

**Comment by Phoenix616** [comment]
What exactly are you trying to do and at which point is the sign text not changed? When it's applied to the world or in a plugin function somewhere?

Because the signs are [changed by using the setSignLine method in the SignChangeEvent](https://github.com/ChestShop-authors/ChestShop-3/blob/29ef7f25aa3c2e54a3eedec5ccbd84a6de55b5ed/src/main/java/com/Acrobot/ChestShop/Listeners/Block/SignCreate.java#L41-L43) so Bukkit is responsible for actually setting the changed lines on the sign in the end.

**Comment by DrOreo002** [comment]
I'm trying this code on PreShopCrationEvent..

for (int i = 0; i < 4; i++) {
  e.setSignLine((byte) i, "");
}

and it should change the sign's text right?. Btw I'm making a shop limiter addon where it will cancel the event and I want to clear the sign's line when player reached the max limit..

But the problem is.., that code is not working and its not changing the sign's text.

Also I'm not on my pc rn, I'm using my phone to reply, I'll continue this tommorow, thanks

**Comment by DrOreo002** [comment]
Btw, I hope I've explained it correctly. I'm not really good at english. Thanks..

**Comment by Phoenix616** [comment]
Yeah I think I see what the issue is. When cancelling the event it will not reach the line setting part. Maybe we should move the sign setting before the return when it's cancelled or cancel the SignChangeEvent too when the PreShopCreationEvent is cancelled. Not sure which the better solution is but the way it's now it's not really practical.

**Comment by DrOreo002** [comment]
Okay I can use my pc now. Here's my code (not working tho), I've tried to cancel the event after I changed the sign.

if (currShop >= limit) {
            player.sendMessage(Main.getPrefix() + "You have reached the max limit of shops creation. Please contact server admin if you need some help.");
            for (int i = 0; i < 4; i++) {
                e.setSignLine((byte) i, "");
            }
            e.setSignLine((byte) 0, "[ Error ]");
            e.setOutcome(PreShopCreationEvent.CreationOutcome.OTHER);
            return;
        }
