### ISSUE TITLE
1.13 ready?

### ISSUE THREAD

**Issue by FrankHeijden** [ChestShop-authors/ChestShop-3#92]
Hey,

Title says it all, but is this plugin already 1.13 ready as of the item ID's?

**Comment by Phoenix616** [comment]
It's not. I have some plans though but parts of it requires knowing how the
1.13 api will look like.

On 31 Dec 2017 2:30 PM, "FrankHeijden" <notifications@github.com> wrote:

Hey,

Title says it all, but is this plugin already 1.13 ready as of the item
ID's?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChestShop-authors/ChestShop-3/issues/92>, or mute the
thread

**Comment by FrankHeijden** [comment]
It uses the api of the latest 1.12.2 builds - depricated stuff in that build about data of itemstacks will be removed in 1.13

**Comment by Phoenix616** [comment]
It's more about the new stuff related to the stuff that will replace the
MaterialData api than some old, deprecated numeric id features (I've
figured that out already)

**Comment by Phoenix616** [comment]
There is now a branch for 1.13 development and first builds are available.

**Comment by kakd** [comment]
I tried build 87 from https://ci.minebench.de/job/ChestShop-3/ and it didn't work for 1.13. Am I looking at the right place?

**Comment by Phoenix616** [comment]
Please always use the latest build when testing (88 at the time you tried it, now 89)

**Comment by Phoenix616** [comment]
1.13 builds should be pretty stable now, closing this.
